# Generated by Django 2.1.5 on 2019-11-21 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_author', models.CharField(db_index=True, max_length=70, verbose_name='Автор')),
                ('biography', models.TextField(null=True, verbose_name='Биография')),
                ('photo', models.ImageField(null=True, upload_to='', verbose_name='Фото')),
                ('dateOfBirth', models.DateField(null=True, verbose_name='Дата рождения')),
                ('debut', models.TextField(null=True, verbose_name='Дебют')),
                ('reaction', models.TextField(null=True, verbose_name='Реакция')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='BookPages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameBook', models.CharField(blank=True, db_index=True, default=None, max_length=64, null=True, verbose_name='Название книги')),
                ('pageBook', models.ImageField(upload_to='', verbose_name='Cтраницы книги')),
            ],
            options={
                'verbose_name': 'Страница книги',
                'verbose_name_plural': 'Страницы книги',
                'ordering': ['nameBook'],
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Облокжка книги')),
                ('nameBook', models.CharField(blank=True, db_index=True, default=None, max_length=64, null=True, verbose_name='Название книги')),
                ('publishingHouse', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Издательсво')),
                ('published', models.DateField(verbose_name='Год издательства')),
                ('language', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Язык')),
                ('pages', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Страниц')),
                ('description', models.TextField(verbose_name='Текст')),
                ('price', models.IntegerField(blank=True, default=None, null=True, verbose_name='Цена')),
                ('is_active', models.BooleanField(default=True, verbose_name='В наличии')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.Author', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('body', models.TextField(verbose_name='Тело комментария')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('active', models.BooleanField(default=True, verbose_name='Показ')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='main.Books')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Картинка жанра')),
                ('genre', models.CharField(db_index=True, max_length=60, verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'ordering': ['genre'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=250, verbose_name='Адрес')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Почтовый индекс')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('paid', models.BooleanField(default=False, verbose_name='Оплачено')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='main.Books', verbose_name='Книга')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.Order', verbose_name='Заказ')),
            ],
        ),
        migrations.AddField(
            model_name='books',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.Genre', verbose_name='Жанр'),
        ),
    ]
