# Generated by Django 2.1.5 on 2019-11-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookpages',
            name='pageBook',
            field=models.FilePathField(verbose_name='Отрывок книги'),
        ),
    ]
